# Generated by Django 4.2.15 on 2024-09-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_default', models.CharField(max_length=100)),
                ('back_female', models.CharField(max_length=100)),
                ('back_shiny', models.CharField(max_length=100)),
                ('back_shiny_female', models.CharField(max_length=100)),
                ('front_default', models.CharField(max_length=100)),
                ('front_female', models.CharField(max_length=100)),
                ('front_shiny', models.CharField(max_length=100)),
                ('front_shiny_female', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sprites',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(db_column='pokemon_id', on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='pokedex.type')),
            ],
            options={
                'db_table': 'pokemon_types',
                'unique_together': {('pokemon', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PokemonSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(db_column='pokemon_id', on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('sprite', models.ForeignKey(db_column='sprite_id', on_delete=django.db.models.deletion.CASCADE, to='pokedex.sprite')),
            ],
            options={
                'db_table': 'pokemon_sprites',
                'unique_together': {('pokemon', 'sprite')},
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(db_column='move_id', on_delete=django.db.models.deletion.CASCADE, to='pokedex.move')),
                ('pokemon', models.ForeignKey(db_column='pokemon_id', on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
            options={
                'db_table': 'pokemon_moves',
                'unique_together': {('pokemon', 'move')},
            },
        ),
    ]
