# Generated by Django 4.2.15 on 2024-09-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_sprite_pokemontype_pokemonsprite_pokemonmove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprite',
            name='back_default',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='back_female',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='back_shiny',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='back_shiny_female',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_default',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_female',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_shiny',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_shiny_female',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
