version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: pokedex
      DB_USER: root
      DB_PASS: root
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"


volumes:
  postgres_data:
